### ISSUE TITLE
Under construction

### ISSUE THREAD

**Issue by milo157** [AyeshaIftikhar/insta_login#4]
**Describe the bug**
I implemented the package as described using the following snippet:

`return InstaView(
instaAppId: Env.instagramAppId,
instaAppSecret:
    Env.instagramAppSecret,
redirectUrl: Env.instagramRedirectUrl,
onComplete: (_token, _userid, _username) {
  WidgetsBinding.instance.addPostFrameCallback(
    (timeStamp) {
      setState(() {
        token = _token;
        userid = _userid;
        username = _username;
      });
    },
  );
},
);`

However, when my screen redirects it just says: "Under contructions".

Since the spelling is incorrect, I am guessing this is coming from your package?

**Comment by milo157** [comment]
@AyeshaIftikhar

**Comment by AyeshaIftikhar** [comment]
Yes perhaps, i am guessing you are not providing a redirect url or you
missing a step and the login isn’t getting through successfully.

Thanks and Regards,
Ayesha Iftikhar

**Comment by milo157** [comment]
I see from your code it appears when I am running on chrome instead of on device. It would be good to update the README with a few things:
- Needs to run on a real iOS/Android device to work
- What is the need for the redirect url and what is the payload you send information to it for

**Comment by AyeshaIftikhar** [comment]
If you have read the package documentation it is currently fully functional
for Android & iOS and It is using Webview services for that purpose. And
you can't use webview on web application. That's why its not working for
you. And the redirect url is for when there is an issue with some of your
integration or the process didn't get through successfully.


Thanks and Regards,
Ayesha Iftikhar
